export const courses = [
  {
    _class: "course",
    id: 10812,
    title: "CCNA 2020 200-125 Video Boot Camp With Chris Bryant",
    url: "/course/ccna-on-demand-video-boot-camp/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 38249,
        title: "Chris Bryant",
        name: "Chris",
        display_name: "Chris Bryant",
        job_title: "Boss Bulldog At The Bryant Advantage",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/38249_92c8_4.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/38249_92c8_4.jpg",
        initials: "CB",
        url: "/user/chrisbryant/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/10812_b0af_6.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/10812_b0af_6.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/10812_b0af_6.jpg",
    published_title: "ccna-on-demand-video-boot-camp",
    tracking_id: "bnC1gmjoSO-pB0QY2fHEBA",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Join The 90,000+ Students Who Are Learning Real-World Skills AND Earning Their CCNA!",
    num_subscribers: 105702,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "pl_PL",
        title: "Polski",
        english_title: "Polish",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
      {
        _class: "locale",
        locale: "ro_RO",
        title: "Română",
        english_title: "Romanian",
      },
      {
        _class: "locale",
        locale: "th_TH",
        title: "ภาษาไทย",
        english_title: "Thai",
      },
    ],
    avg_rating: 4.5588236,
    avg_rating_recent: 4.539888,
    rating: 4.539888,
    num_reviews: 25165,
    is_wishlisted: false,
    num_published_lectures: 467,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/10812_b0af_6.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/10812_b0af_6.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/10812_b0af_6.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/10812_b0af_6.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "Indonesian [Auto]",
      "Italian [Auto]",
      "Polish [Auto]",
      "Portuguese [Auto]",
      "Romanian [Auto]",
      "Spanish [Auto]",
      "Thai [Auto]",
    ],
    created: "2011-11-03T22:36:26Z",
    instructional_level: "Beginner Level",
    instructional_level_simple: "Beginner",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2012-01-05T14:11:39Z",
    objectives_summary: [],
    is_recently_published: false,
    last_update_date: "2018-08-03",
    preview_url: "/course/10812/preview/",
    learn_url: "/course/ccna-on-demand-video-boot-camp/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "62.5 total hours",
    content_info_short: "62.5 hours",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5044,
        display_name: "Cisco CCNA",
        title: "Cisco CCNA",
        topic_channel_url: "/topic/cisco-ccna/",
        url: "/topic/cisco-ccna/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 16429,
    title: "CCNP All-in-1 Video Boot Camp With Chris Bryant",
    url: "/course/ccnpallinone/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 38249,
        title: "Chris Bryant",
        name: "Chris",
        display_name: "Chris Bryant",
        job_title: "Boss Bulldog At The Bryant Advantage",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/38249_92c8_4.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/38249_92c8_4.jpg",
        initials: "CB",
        url: "/user/chrisbryant/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/16429_c92e_5.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/16429_c92e_5.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/16429_c92e_5.jpg",
    published_title: "ccnpallinone",
    tracking_id: "b4q_dBMUTqOUR7UQvxeL6A",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Earn Your CCNP With Chris Bryant ! Pass SWITCH 300-115, ROUTE 300-101, and TSHOOT 300-135!",
    num_subscribers: 47215,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "pl_PL",
        title: "Polski",
        english_title: "Polish",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
      {
        _class: "locale",
        locale: "ro_RO",
        title: "Română",
        english_title: "Romanian",
      },
      {
        _class: "locale",
        locale: "th_TH",
        title: "ภาษาไทย",
        english_title: "Thai",
      },
    ],
    avg_rating: 4.445652,
    avg_rating_recent: 4.480544,
    rating: 4.480544,
    num_reviews: 8272,
    is_wishlisted: false,
    num_published_lectures: 438,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/16429_c92e_5.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/16429_c92e_5.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/16429_c92e_5.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/16429_c92e_5.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "Indonesian [Auto]",
      "Italian [Auto]",
      "Polish [Auto]",
      "Portuguese [Auto]",
      "Romanian [Auto]",
      "Spanish [Auto]",
      "Thai [Auto]",
    ],
    created: "2012-04-16T15:17:33Z",
    instructional_level: "Intermediate Level",
    instructional_level_simple: "Intermediate",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2012-05-26T20:18:39Z",
    objectives_summary: [],
    is_recently_published: false,
    last_update_date: "2018-08-05",
    preview_url: "/course/16429/preview/",
    learn_url: "/course/ccnpallinone/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "62 total hours",
    content_info_short: "62 hours",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "121935fa0dbd41878c797cd4b58c46f8",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 143592,
          display_name: "CCNP Enterprise",
          title: "CCNP Enterprise",
          topic_channel_url: "/topic/ccnp-enterprise/",
          url: "/topic/ccnp-enterprise/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "121935fa0dbd41878c797cd4b58c46f8",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 143592,
            display_name: "CCNP Enterprise",
            title: "CCNP Enterprise",
            topic_channel_url: "/topic/ccnp-enterprise/",
            url: "/topic/ccnp-enterprise/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 143592,
        display_name: "CCNP Enterprise",
        title: "CCNP Enterprise",
        topic_channel_url: "/topic/ccnp-enterprise/",
        url: "/topic/ccnp-enterprise/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 22591,
    title: "Introduction To Fiber Optic Cabling ",
    url: "/course/introduction-to-fiber-optic-cabling/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 112913,
        title: "Sebastian Flores",
        name: "Sebastian",
        display_name: "Sebastian Flores",
        job_title: "Fiber Optics Instructor",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/112913_7314_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/112913_7314_2.jpg",
        initials: "SF",
        url: "/user/sebastianflores/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/22591_b568_6.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/22591_b568_6.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/22591_b568_6.jpg",
    published_title: "introduction-to-fiber-optic-cabling",
    tracking_id: "ZVp9_Kx8Rz6_5zuYN2191w",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Welcome! This course is designed to give you a good understand of fiber optics and fiber data transmission.",
    num_subscribers: 9663,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
    ],
    avg_rating: 4.4446106,
    avg_rating_recent: 4.4408946,
    rating: 4.4408946,
    num_reviews: 3738,
    is_wishlisted: false,
    num_published_lectures: 12,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/22591_b568_6.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/22591_b568_6.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/22591_b568_6.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/22591_b568_6.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English [Auto]"],
    created: "2012-08-10T05:30:51Z",
    instructional_level: "All Levels",
    instructional_level_simple: "All Levels",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2014-01-27T07:55:03Z",
    objectives_summary: [
      "By the end of this course you should have a good understanding of fiber optic cabling.",
    ],
    is_recently_published: false,
    last_update_date: "2014-01-28",
    preview_url: "/course/22591/preview/",
    learn_url: "/course/introduction-to-fiber-optic-cabling/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "41 total mins",
    content_info_short: "41 mins",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8016,
        display_name: "Telecom",
        title: "Telecom",
        topic_channel_url: "/topic/telecom/",
        url: "/topic/telecom/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 32199,
    title: "IT Troubleshooting Skill Training ",
    url: "/course/it-troubleshooting/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 476818,
        title: "Noel Temena",
        name: "Noel",
        display_name: "Noel Temena",
        job_title: "Deductive Skill Training, Corporate Coach & Tool Builder",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/476818_c461_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/476818_c461_3.jpg",
        initials: "NT",
        url: "/user/noeltemena/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/32199_6ad0_6.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/32199_6ad0_6.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/32199_6ad0_6.jpg",
    published_title: "it-troubleshooting",
    tracking_id: "z8NVACcvR6uL5ausq81hyA",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline: "IT Troubleshooting 101 for Analysts and Managers ",
    num_subscribers: 34455,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "nl_NL",
        title: "Nederlands",
        english_title: "Dutch",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
      {
        _class: "locale",
        locale: "th_TH",
        title: "ภาษาไทย",
        english_title: "Thai",
      },
    ],
    avg_rating: 4.393453,
    avg_rating_recent: 4.3661366,
    rating: 4.3661366,
    num_reviews: 10228,
    is_wishlisted: false,
    num_published_lectures: 16,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/32199_6ad0_6.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/32199_6ad0_6.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/32199_6ad0_6.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/32199_6ad0_6.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "Dutch [Auto]",
      "French [Auto]",
      "German [Auto]",
      "Indonesian [Auto]",
      "Italian [Auto]",
      "Korean [Auto]",
      "Portuguese [Auto]",
      "Spanish [Auto]",
      "Thai [Auto]",
    ],
    created: "2012-12-10T19:59:52Z",
    instructional_level: "Intermediate Level",
    instructional_level_simple: "Intermediate",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-02-24T22:41:58Z",
    objectives_summary: [
      "Minimize problem duration",
      "Standardize troubleshooting procedure",
      "Practice efficient problem identification",
    ],
    is_recently_published: false,
    last_update_date: "2024-02-19",
    preview_url: "/course/32199/preview/",
    learn_url: "/course/it-troubleshooting/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "1.5 total hours",
    content_info_short: "1.5 hours",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 35306,
        display_name: "IT Troubleshooting",
        title: "IT Troubleshooting",
        topic_channel_url: "/topic/it-troubleshooting/",
        url: "/topic/it-troubleshooting/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 53911,
    title: "The Theory Behind Electronics - A Beginners Guide",
    url: "/course/the-theory-behind-electronics-a-beginners-guide/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 359707,
        title: "Idan Gabrieli",
        name: "Idan",
        display_name: "Idan Gabrieli",
        job_title: "Online Teacher | Data, Cloud, AI",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/359707_d8b2_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/359707_d8b2_3.jpg",
        initials: "IG",
        url: "/user/idangabrieli/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/53911_4529_2.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/53911_4529_2.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/53911_4529_2.jpg",
    published_title: "the-theory-behind-electronics-a-beginners-guide",
    tracking_id: "VwYWcEElTVmBkpD6wu2RoA",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Start your Journey in Electronics with a Solid Background - Current, Voltage, Resistance and Power",
    num_subscribers: 14171,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "zh_CN",
        title: "中文(简体)",
        english_title: "Simplified Chinese (China)",
      },
    ],
    avg_rating: 4.4711537,
    avg_rating_recent: 4.5302,
    rating: 4.5302,
    num_reviews: 921,
    is_wishlisted: false,
    num_published_lectures: 62,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/53911_4529_2.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/53911_4529_2.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/53911_4529_2.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/53911_4529_2.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English", "Simplified Chinese [Auto]"],
    created: "2013-05-14T07:44:28Z",
    instructional_level: "Beginner Level",
    instructional_level_simple: "Beginner",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2016-04-06T23:28:33Z",
    objectives_summary: [
      "Understand the R, L, C building blocks of analog electronics",
      "Calculate Voltage, Current and Power and understand the relation between them",
      "Understand the properties of DC and AC power supply",
    ],
    is_recently_published: false,
    last_update_date: "2023-10-27",
    preview_url: "/course/53911/preview/",
    learn_url: "/course/the-theory-behind-electronics-a-beginners-guide/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "3.5 total hours",
    content_info_short: "3.5 hours",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5580,
        display_name: "Electronics",
        title: "Electronics",
        topic_channel_url: "/topic/electronics/",
        url: "/topic/electronics/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 55282,
    title: "Information Technology Essentials",
    url: "/course/information-technology-essentials/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 783759,
        title: "Destin Learning",
        name: "Destin",
        display_name: "Destin Learning",
        job_title: "Learning Sans Location",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/783759_996f_5.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/783759_996f_5.jpg",
        initials: "DL",
        url: "/user/ericfrick/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/55282_cbd6_13.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/55282_cbd6_13.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/55282_cbd6_13.jpg",
    published_title: "information-technology-essentials",
    tracking_id: "8DAnQZRBS7akWLDnASddQg",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline: "Introduction to Information Technology and Information Systems",
    num_subscribers: 4615,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
    ],
    avg_rating: 4.74,
    avg_rating_recent: 4.713002,
    rating: 4.713002,
    num_reviews: 644,
    is_wishlisted: false,
    num_published_lectures: 51,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/55282_cbd6_13.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/55282_cbd6_13.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/55282_cbd6_13.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/55282_cbd6_13.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English [Auto]"],
    created: "2013-05-20T13:40:26Z",
    instructional_level: "Beginner Level",
    instructional_level_simple: "Beginner",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2017-03-01T22:47:48Z",
    objectives_summary: [
      "You will also learn some of the history of computing and some of the emerging technologies.",
      "By the end of the course you will have a solid understanding major information systems concepts.",
      "In this course you will learn how software is developed, the basic operation of a computer and how networks function.",
    ],
    is_recently_published: false,
    last_update_date: "2024-05-25",
    preview_url: "/course/55282/preview/",
    learn_url: "/course/information-technology-essentials/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "4.5 total hours",
    content_info_short: "4.5 hours",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 6316,
        display_name: "IT Fundamentals",
        title: "IT Fundamentals",
        topic_channel_url: "/topic/it-fundamentals/",
        url: "/topic/it-fundamentals/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 62109,
    title: "Computer Forensics Fundamentals",
    url: "/course/computer-forensics-fundamentals/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 907400,
        title: "John Boyle",
        name: "John",
        display_name: "John Boyle",
        job_title:
          "IT and Business Professional, Database Developer, ACE, ENCE",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/907400_0beb_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/907400_0beb_3.jpg",
        initials: "JB",
        url: "/user/johnboyle3/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/62109_9be0_8.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/62109_9be0_8.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/62109_9be0_8.jpg",
    published_title: "computer-forensics-fundamentals",
    tracking_id: "VmhuXsLSRemk7oBctRd2dg",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "An introduction to Computer Forensics, to demonstrate the process of going from the crime scene to the court room.",
    num_subscribers: 36779,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
    ],
    avg_rating: 4.4346557,
    avg_rating_recent: 4.4371285,
    rating: 4.4371285,
    num_reviews: 16971,
    is_wishlisted: false,
    num_published_lectures: 18,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/62109_9be0_8.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/62109_9be0_8.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/62109_9be0_8.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/62109_9be0_8.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "French [Auto]",
      "German [Auto]",
      "Indonesian [Auto]",
      "Italian [Auto]",
      "Portuguese [Auto]",
      "Spanish [Auto]",
    ],
    created: "2013-06-25T17:14:43Z",
    instructional_level: "Beginner Level",
    instructional_level_simple: "Beginner",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-11-12T15:40:57Z",
    objectives_summary: [
      "Understanding what computer forensics is",
      "Be able to make a forensics image from a drive",
      "Be able to mount a drive for analysis",
    ],
    is_recently_published: false,
    last_update_date: "2020-07-07",
    preview_url: "/course/62109/preview/",
    learn_url: "/course/computer-forensics-fundamentals/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "1 total hour",
    content_info_short: "1 hour",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "9a72daeba86f455e921e61f487c5f51d",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 5186,
          display_name: "Computer Forensics",
          title: "Computer Forensics",
          topic_channel_url: "/topic/computer-forensics/",
          url: "/topic/computer-forensics/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "9a72daeba86f455e921e61f487c5f51d",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 5186,
            display_name: "Computer Forensics",
            title: "Computer Forensics",
            topic_channel_url: "/topic/computer-forensics/",
            url: "/topic/computer-forensics/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5186,
        display_name: "Computer Forensics",
        title: "Computer Forensics",
        topic_channel_url: "/topic/computer-forensics/",
        url: "/topic/computer-forensics/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 65618,
    title: "Mastering Modbus RS485 Network Communication",
    url: "/course/mastering-modbus-rs485-network-communication/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 209114,
        title: "Emile Ackbarali",
        name: "Emile",
        display_name: "Emile Ackbarali",
        job_title: "Software Developer, Systems Integrator and Entrepreneur",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/209114_2733_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/209114_2733_3.jpg",
        initials: "EA",
        url: "/user/emileackbarali/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/65618_be53_7.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/65618_be53_7.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/65618_be53_7.jpg",
    published_title: "mastering-modbus-rs485-network-communication",
    tracking_id: "o0DyoVrtTfSbNzFkDvihog",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Learn how to design, implement and manage the most popular automation networking system in the world.",
    num_subscribers: 9464,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
    ],
    avg_rating: 4.7,
    avg_rating_recent: 4.708897,
    rating: 4.708897,
    num_reviews: 3166,
    is_wishlisted: false,
    num_published_lectures: 88,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/65618_be53_7.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/65618_be53_7.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/65618_be53_7.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/65618_be53_7.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English"],
    created: "2013-07-15T19:07:05Z",
    instructional_level: "Intermediate Level",
    instructional_level_simple: "Intermediate",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-08-05T01:20:25Z",
    objectives_summary: [
      "The Origins of the Modbus Protocol and RS485",
      "Understand Memory Address vs. Memory Value",
      "Memory Addressing Conventions",
    ],
    is_recently_published: false,
    last_update_date: "2022-08-21",
    preview_url: "/course/65618/preview/",
    learn_url: "/course/mastering-modbus-rs485-network-communication/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "4 total hours",
    content_info_short: "4 hours",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "60bed2cfc0294fd9aa47cc91abcfa792",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 22286,
          display_name: "Modbus",
          title: "Modbus",
          topic_channel_url: "/topic/modbus/",
          url: "/topic/modbus/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "60bed2cfc0294fd9aa47cc91abcfa792",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 22286,
            display_name: "Modbus",
            title: "Modbus",
            topic_channel_url: "/topic/modbus/",
            url: "/topic/modbus/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 22286,
        display_name: "Modbus",
        title: "Modbus",
        topic_channel_url: "/topic/modbus/",
        url: "/topic/modbus/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 76838,
    title: "Master Computers - From Beginner to Expert in One Week",
    url: "/course/computers/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 710121,
        title: "Todd McLeod",
        name: "Todd",
        display_name: "Todd McLeod",
        job_title: "Top-Rated Instructor, Tenured College Professor",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/710121_fdc7_6.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/710121_fdc7_6.jpg",
        initials: "TM",
        url: "/user/toddmcleod/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/76838_e5b4_6.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/76838_e5b4_6.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/76838_e5b4_6.jpg",
    published_title: "computers",
    tracking_id: "zta6w4_tS_quiju46G-dZA",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "Become a master of computers. In one week, you will understand how computers work and how to use them well.",
    num_subscribers: 58234,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
    ],
    avg_rating: 4.340206,
    avg_rating_recent: 4.218795,
    rating: 4.218795,
    num_reviews: 3962,
    is_wishlisted: false,
    num_published_lectures: 329,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/76838_e5b4_6.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/76838_e5b4_6.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/76838_e5b4_6.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/76838_e5b4_6.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English [Auto]"],
    created: "2013-08-10T21:29:01Z",
    instructional_level: "All Levels",
    instructional_level_simple: "All Levels",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-08-11T19:27:36Z",
    objectives_summary: [
      "Learn from a highly rated instructor with over 20 years of experience teaching individuals of all ability levels.",
      "From the fundamentals, to the most advanced features, this course covers everything you need to know to use computers well.",
      "Learn incredibly valuable hands-on computer skills.",
    ],
    is_recently_published: false,
    last_update_date: "2022-04-20",
    preview_url: "/course/76838/preview/",
    learn_url: "/course/computers/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "38 total hours",
    content_info_short: "38 hours",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "a560aa0c51dd4990b9923c4100c52c8f",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 11272,
          display_name: "Computer Skills",
          title: "Computer Skills",
          topic_channel_url: "/topic/computer-skills/",
          url: "/topic/computer-skills/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "a560aa0c51dd4990b9923c4100c52c8f",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 11272,
            display_name: "Computer Skills",
            title: "Computer Skills",
            topic_channel_url: "/topic/computer-skills/",
            url: "/topic/computer-skills/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 11272,
        display_name: "Computer Skills",
        title: "Computer Skills",
        topic_channel_url: "/topic/computer-skills/",
        url: "/topic/computer-skills/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 88188,
    title: "Learn 5 PLCs in a Day-AB, Siemens, Schneider, Omron & Delta",
    url: "/course/nfi-plc-online-leaning/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 46580342,
        title: "Rajvir Singh",
        name: "Rajvir",
        display_name: "Rajvir Singh",
        job_title: "Founder, Code and Compile",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/46580342_e62f_4.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/46580342_e62f_4.jpg",
        initials: "RS",
        url: "/user/rajvir-singh-13/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/88188_c111_13.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/88188_c111_13.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/88188_c111_13.jpg",
    published_title: "nfi-plc-online-leaning",
    tracking_id: "S3ubCDZpSrGSmG4KA9V8FQ",
    locale: {
      _class: "locale",
      locale: "en_IN",
      title: "English (India)",
      english_title: "English (India)",
      simple_english_title: "English",
    },
    headline:
      "PLC Programming of Allen Bradley, Delta, Siemens, Omron & Schneider using LIVE Examples with HMI Interfacing",
    num_subscribers: 29873,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_IN",
        title: "English (India)",
        english_title: "English (India)",
      },
      {
        _class: "locale",
        locale: "ja_JP",
        title: "日本語",
        english_title: "Japanese",
      },
      {
        _class: "locale",
        locale: "zh_CN",
        title: "中文(简体)",
        english_title: "Simplified Chinese (China)",
      },
    ],
    avg_rating: 4.6307693,
    avg_rating_recent: 4.622949,
    rating: 4.622949,
    num_reviews: 5389,
    is_wishlisted: false,
    num_published_lectures: 307,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/88188_c111_13.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/88188_c111_13.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/88188_c111_13.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/88188_c111_13.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "Japanese [Auto]",
      "Simplified Chinese [Auto]",
    ],
    created: "2013-09-04T17:56:32Z",
    instructional_level: "All Levels",
    instructional_level_simple: "All Levels",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-11-03T09:03:04Z",
    objectives_summary: [
      "To Learn Ladder Logic Programming",
      "PLC Wiring Concepts & Troubleshooting",
      "To Teach Programming to Technician & Engineer",
    ],
    is_recently_published: false,
    last_update_date: "2024-05-20",
    preview_url: "/course/88188/preview/",
    learn_url: "/course/nfi-plc-online-leaning/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "44.5 total hours",
    content_info_short: "44.5 hours",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "2628b614e93047388f77da0c95d6f1f1",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 15282,
          display_name: "HMI",
          title: "HMI",
          topic_channel_url: "/topic/hmi/",
          url: "/topic/hmi/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "8a810925df814b818ca042ff329b6d83",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 15282,
            display_name: "HMI",
            title: "HMI",
            topic_channel_url: "/topic/hmi/",
            url: "/topic/hmi/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 7216,
        display_name: "PLC",
        title: "PLC",
        topic_channel_url: "/topic/plc/",
        url: "/topic/plc/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 95246,
    title: "Linux Command Line Basics",
    url: "/course/linux-command-line-volume1/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 1121754,
        title: "Ahmed Alkabary",
        name: "Ahmed",
        display_name: "Ahmed Alkabary",
        job_title: "DevOps Engineer @Boeing - 240,000+ Happy Students.",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/1121754_f082_12.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/1121754_f082_12.jpg",
        initials: "AA",
        url: "/user/ahmedalkabary/",
      },
      {
        _class: "user",
        id: 232482692,
        title: "Abdullah Tarek",
        name: "Abdullah",
        display_name: "Abdullah Tarek",
        job_title: "DevOps Engineer",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/232482692_4db7.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/232482692_4db7.jpg",
        initials: "AT",
        url: "/user/abdullah-tarek-20/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/95246_69f4_23.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/95246_69f4_23.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/95246_69f4_23.jpg",
    published_title: "linux-command-line-volume1",
    tracking_id: "InxWjuFjQMG6-y0Okkrgbw",
    locale: {
      _class: "locale",
      locale: "en_US",
      title: "English (US)",
      english_title: "English (US)",
      simple_english_title: "English",
    },
    headline:
      "This is an introductory course to the Linux command Line. It's great for both Linux beginners and advanced Linux users.",
    num_subscribers: 194519,
    caption_locales: [
      {
        _class: "locale",
        locale: "bg_BG",
        title: "Български",
        english_title: "Bulgarian",
      },
      {
        _class: "locale",
        locale: "cs_CZ",
        title: "Čeština",
        english_title: "Czech",
      },
      {
        _class: "locale",
        locale: "da_DK",
        title: "Dansk",
        english_title: "Danish",
      },
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "el_GR",
        title: "Ελληνικά",
        english_title: "Greek",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "et_EE",
        title: "Eesti",
        english_title: "Estonian",
      },
      {
        _class: "locale",
        locale: "fi_FI",
        title: "Suomi",
        english_title: "Finnish",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "hu_HU",
        title: "Magyar",
        english_title: "Hungarian",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "lt_LT",
        title: "Lietuvių",
        english_title: "Lithuanian",
      },
      {
        _class: "locale",
        locale: "lv_LV",
        title: "Latviešu",
        english_title: "Latvian",
      },
      {
        _class: "locale",
        locale: "nl_NL",
        title: "Nederlands",
        english_title: "Dutch",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
      {
        _class: "locale",
        locale: "ro_RO",
        title: "Română",
        english_title: "Romanian",
      },
      {
        _class: "locale",
        locale: "sk_SK",
        title: "Slovenčina",
        english_title: "Slovak",
      },
      {
        _class: "locale",
        locale: "sv_SE",
        title: "Svenska",
        english_title: "Swedish",
      },
      {
        _class: "locale",
        locale: "uk_UA",
        title: "Українська",
        english_title: "Ukrainian",
      },
      {
        _class: "locale",
        locale: "zh_CN",
        title: "中文(简体)",
        english_title: "Simplified Chinese (China)",
      },
    ],
    avg_rating: 4.552198,
    avg_rating_recent: 4.5462165,
    rating: 4.5462165,
    num_reviews: 29587,
    is_wishlisted: false,
    num_published_lectures: 41,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/95246_69f4_23.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/95246_69f4_23.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/95246_69f4_23.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/95246_69f4_23.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "English [Auto]",
      "Bulgarian [Auto]",
      "Czech [Auto]",
      "Danish [Auto]",
      "Dutch [Auto]",
      "Estonian [Auto]",
      "Finnish [Auto]",
      "French [Auto]",
      "German [Auto]",
      "Greek [Auto]",
      "Hungarian [Auto]",
      "Indonesian [Auto]",
      "Italian [Auto]",
      "Latvian [Auto]",
      "Lithuanian [Auto]",
      "Portuguese [Auto]",
      "Romanian [Auto]",
      "Simplified Chinese [Auto]",
      "Slovak [Auto]",
      "Spanish [Auto]",
      "Swedish [Auto]",
      "Ukrainian [Auto]",
    ],
    created: "2013-09-21T09:50:56Z",
    instructional_level: "All Levels",
    instructional_level_simple: "All Levels",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2013-09-25T02:42:44Z",
    objectives_summary: [
      "realize the potential of the Linux command line.",
      "navigating the Linux Filesystem.",
      "explain the Linux Filesystem hierarchy.",
    ],
    is_recently_published: false,
    last_update_date: "2021-10-12",
    preview_url: "/course/95246/preview/",
    learn_url: "/course/linux-command-line-volume1/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "5 total hours",
    content_info_short: "5 hours",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "85ee43c24d404b9cb81b5637e7df8850",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 294,
          title: "IT & Software",
          url: "/courses/it-and-software/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: {
          id: 5154,
          display_name: "Command Line",
          title: "Command Line",
          topic_channel_url: "/topic/command-line/",
          url: "/topic/command-line/",
          tracking_object_type: "cl",
        },
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "85ee43c24d404b9cb81b5637e7df8850",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "IT & Software",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 5154,
            display_name: "Command Line",
            title: "Command Line",
            topic_channel_url: "/topic/command-line/",
            url: "/topic/command-line/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5154,
        display_name: "Command Line",
        title: "Command Line",
        topic_channel_url: "/topic/command-line/",
        url: "/topic/command-line/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    _class: "course",
    id: 98434,
    title: "Unix For Beginners",
    url: "/course/unix-for-beginners/",
    is_paid: true,
    visible_instructors: [
      {
        _class: "user",
        id: 1230724,
        title: "Skill Tree",
        name: "Skill",
        display_name: "Skill Tree",
        job_title: "Skill based learning",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/1230724_3979_8.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/1230724_3979_8.jpg",
        initials: "ST",
        url: "/user/williamumusu/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/98434_d5d1_3.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/98434_d5d1_3.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/98434_d5d1_3.jpg",
    published_title: "unix-for-beginners",
    tracking_id: "RwgiZyKBShaSldgq7YXZTg",
    locale: {
      _class: "locale",
      locale: "en_GB",
      title: "English (UK)",
      english_title: "English (UK)",
      simple_english_title: "English",
    },
    headline: "Absolute beginners to Unix - Learn the basic Unix Commands",
    num_subscribers: 12514,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_GB",
        title: "English (UK)",
        english_title: "English (UK)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
    ],
    avg_rating: 4.3970895,
    avg_rating_recent: 4.4058094,
    rating: 4.4058094,
    num_reviews: 3485,
    is_wishlisted: false,
    num_published_lectures: 41,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/98434_d5d1_3.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/98434_d5d1_3.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/98434_d5d1_3.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/98434_d5d1_3.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["English [Auto]", "French [Auto]", "Spanish [Auto]"],
    created: "2013-09-27T16:49:44Z",
    instructional_level: "Beginner Level",
    instructional_level_simple: "Beginner",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2016-03-14T22:46:07Z",
    objectives_summary: [
      "Define Unix",
      "Know of different types of Unix",
      "Know the parts of Unix",
    ],
    is_recently_published: false,
    last_update_date: "2024-01-08",
    preview_url: "/course/98434/preview/",
    learn_url: "/course/unix-for-beginners/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "3 total hours",
    content_info_short: "3 hours",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 294,
        title: "IT & Software",
        url: "/courses/it-and-software/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8164,
        display_name: "Unix",
        title: "Unix",
        topic_channel_url: "/topic/unix/",
        url: "/topic/unix/",
        tracking_object_type: "cl",
      },
    },
  },
];
